#name: ğŸš€ FTP Deploy
##on: [push, workflow_dispatch]
#on: [push]
#jobs:
#  ftp-deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: ğŸšš Get latest code
#        uses: actions/checkout@v2
#      - name: ğŸ“¦ Get LFTP
#        run: sudo apt install lftp
#      - name: ğŸ› ï¸ Configure LFTP
#        run: mkdir ~/.lftp && echo "set ssl:verify-certificate false;" >> ~/.lftp/rc
#      - name: ğŸ”‘ Load Secrets
#        run: echo "machine ${{ secrets.FTP_HOSTNAME }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc
#      #- name: ğŸ“„ Upload File
#      #  run: lftp -e "mput -O /domains/anugraha.nl/public_html/ README.md" ${{ secrets.FTP_HOSTNAME }}
#      - name: ğŸ“ Upload Folder
#        run: lftp -e "mirror --parallel=100 -R ./ /domains/anugraha.nl/public_html/" ${{ secrets.FTP_HOSTNAME }}
